### ISSUE TITLE
Usage of gethostbyname leads to occasional segfaults

### ISSUE THREAD

**Issue by dtascione** [carnegierobotics/LibMultiSense#107]
It looks like `crl::multisense::Channel` is using `gethostbyname`. If you have multiple instances of `Channel` (or are in another process that is also using `gethostbyname`), then you will get segfaults (occasionally) when trying to access the returned pointers.

This is particularly reproducible if you have many instances (3-6) in a single process, and the cameras are all turned off.

There are a few solutions (`gethostbyname_r` or `getaddrinfo`) -- we patched it internally, but I wasn't sure if those APIs were supported on all of your platforms.

**Comment by mattalvarado** [comment]
Thanks for the bug report @dtascione. I will do some testing tomorrow and check this out.

**Comment by mattalvarado** [comment]
This should be resolved!
