### ISSUE TITLE
Please expose independent exposure controls for mono vs color imagers

### ISSUE THREAD

**Issue by pdlr** [carnegierobotics/LibMultiSense#32]
Users often need to set different exposure settings (including ROI) for the stereo imagers and the color imagers, but libmultisense does not yet support this.  Can you please add this capability?
Thank you.

**Comment by mattalvarado** [comment]
@pdlr I believe this PR addresses this: https://github.com/carnegierobotics/LibMultiSense/pull/29

**Comment by mattalvarado** [comment]
> @pdlr I believe this PR addresses this: #29

Sorry, this just handles ROI control. I imagine a similar interface for the rest of the exposure controls

**Comment by pdlr** [comment]
> @pdlr I believe this PR addresses this: #29

@mattalvarado Thanks for linking this PR.  I was not aware of it.  Seems like we're half-way there on this issue already!

**Comment by QuentinTorg** [comment]
Closed by #33
