### ISSUE TITLE
Can't compile multisense lib using visual studio 2019

### ISSUE THREAD

**Issue by tomaspoupin** [carnegierobotics/LibMultiSense#63]
When trying to compile the library, i get include path errors, this is mainly because the MultiSense symbolic link is not treated as such on windows, so the compiler fails to locate the files. A fast fix I used is to create a folder named MultiSense and copy the contents of LibMultiSense into MultiSense

**Comment by mattalvarado** [comment]
Hi @tomaspoupin. Thanks for your report. We are in the process of fixing this now. Can you try https://github.com/carnegierobotics/LibMultiSense/pull/62 on your machine?

**Comment by mattalvarado** [comment]
@tomaspoupin This fix is now landed on master. Please let us know if you have any issues. Apologies for the issue you experienced.

**Comment by tomaspoupin** [comment]
Hi @mattalvarado, I tried rebuilding the project this morning and everything seems to be working ok! Thank you for the fix.
