### ISSUE TITLE
Lib multisense time sync takes a long time when system clock jumps

### ISSUE THREAD

**Issue by erandtkecr** [carnegierobotics/LibMultiSense#76]
The lib multisense library takes 1 to 2 minutes to time sync when booting the thoro pallet jack system.  Multisense is interfaced via the ark system.

Is there a new library we can use, or some way to make time sync faster?

**Comment by dtascione** [comment]
I haven't looked into this issue personally, but I believe the underlying cause for this is that the libMultiSense code will synchronize time using the `system_clock`, and there is a big system time jump on startup shortly after the system starts / we get wifi. It looks like the 'decayed average' mechanism used isn't handling large jumps very well and is taking a while to converge after a jump takes place. One potential easy fix might be to just re-seed on large jumps (although the decayed average code being used right now makes fairly small adjustments, it might be worth reviewing that to determine if that is intended).

Regardless, it would *also* be great if libMultiSense could synchronize time using the `steady_clock` instead. We previously applied a patch to it to do just that, but found that on freshly booted systems, the offset from the multisense to the compute host would actually be negative (ie, the line `const utility::TimeStamp offset = ping + latency - msg.uptime;` was yielding a negative offset, as `ping + latency` was less then `msg.uptime`, which wouldn't normally happen if ping was a large system time, but did happen always when it was a tiny steady time). This seemed to cause a few underflow/overflow issues in a few spots dealing with `TimeStamp`, but I didn't really dig into it any further, I just reverted our patch.
